name: Build and Release Images

on:
  push:
    branches:
      - main
    paths:
      - release.arg

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1.0.4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Images
        run: earthly --arg-file-path=release.arg --ci

      - name: Push to GitHub Container Registry
        run: earthly --arg-file-path=release.arg --ci --push +docker
